using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestDemo.Models
{

    public class MediaQCTrans
    {
        public string EPISODE_ID { set; get; }
        public string FILM_ID { set; get; }
        public string MOVIE_TITLE { set; get; }
        public string EPISODE_TITLE { set; get; }
        public string MEDIA_ID { set; get; }
        public string MAM_HOUSENUMBER { set; get; }
        public string STOCK_MAT_HOUSENO { set; get; }
        public string MAT_HOUSENO { set; get; }
        public string STOCK_MATERIALID { set; get; }
        public string SCH_STATUS { set; get; }
        public string QC_SCH_STATUS { set; get; }
        public string ROW_ID_QC_HDR { set; get; }
        public double REVISION_NO { set; get; }
        public string MATERIAL_ID { get; set; }
        public string RID_QC_HDR { get; set; }
        public string QC_SCH_STATUS_CODE { get; set; }
        public string QC_TECH_USER { get; set; }
        public DateTime? QC_TECH_DATE { get; set; }
        public string COLOR_BAR_FLAG { get; set; }
        public string COLOR_BAR_STD { get; set; }
        public double COLOR_PERCENTAGE { get; set; }
        public string BLACK_BAR_FLAG { get; set; }
        public string BLACK_BAR_STD { get; set; }
        public double BLACK_PERCENTAGE { get; set; }
        public string AUDIO_TONE_FLAG { get; set; }
        public string AUDIO_TONE_STD { get; set; }
        public double AUDIO_TONE_PERCENTAGE { get; set; }
        public string OBB_FLAG { get; set; }
        public string OBB_STD { get; set; }
        public double OBB_PERCENTAGE { get; set; }
        public string LUMINANCE_LEVEL { get; set; }
        public string CHROMA_LEVEL { get; set; }
        public string BLACK_LEVEL { get; set; }
        public string MONO { get; set; }
        public string STEREO { get; set; }
        public string BILINGUAL { get; set; }
        public string CH1_FLAG { get; set; }
        public string CH2_FLAG { get; set; }
        public string CH3_FLAG { get; set; }
        public string CH4_FLAG { get; set; }
        public string AUDIO_SIGNAL_CH1 { get; set; }
        public string AUDIO_SIGNAL_CH2 { get; set; }
        public string AUDIO_SIGNAL_CH3 { get; set; }
        public string AUDIO_SIGNAL_CH4 { get; set; }
        public string VIDEO_LEVEL { get; set; }
        public string V_CHROMA_LEVEL { get; set; }
        public string CHROMA_PHRASE { get; set; }
        public string CHROMA_DELAY { get; set; }
        public string REGISTRATION { get; set; }
        public string COLOR_BALANCE { get; set; }
        public string RESOLUTION { get; set; }
        public string FOCUS { get; set; }
        public string NOISE { get; set; }
        public string STREAKING { get; set; }
        public string HUM { get; set; }
        public string MOIRE { get; set; }
        public string FLICKER { get; set; }
        public string PULSE_NOISE { get; set; }
        public string V_OTHER { get; set; }
        public string FRAME_FLAG { get; set; }
        public string AUDIO_LEVEL { get; set; }
        public string INTELLIGIBILITY { get; set; }
        public string DISTORTION { get; set; }
        public string NOISE_HUM { get; set; }
        public string BALANCE { get; set; }
        public string LIP_SYNC { get; set; }
        public string STEREO_PHASE { get; set; }
        public string CONTENTS { get; set; }
        public string DUB { get; set; }
        public string TIME_CODE { get; set; }
        public string TRACKING { get; set; }
        public string RF_LEVEL { get; set; }
        public string SERVO_LOCK { get; set; }
        public string TAPE_STOCK { get; set; }
        public string EDITING { get; set; }
        public string QC_COMMENTS { get; set; }
        public DateTime? UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string ROW_ID { get; set; }
        public string AUDIO { get; set; }
        public string VIDEO { get; set; }
        public string QC_TIME { get; set; }
        public string QC_USER { get; set; }
        public string EVALUATION { get; set; }
        public string TS_BLACK_LEVEL { get; set; }
        public string VJERKY { get; set; }
        public string AJERKY { get; set; }
        public string TCTYPE { get; set; }
        public string FREQUENCY { get; set; }
        public string ENGLISH_COM { get; set; }
        public string ATMOSPHERE { get; set; }
        public string AUDIO_SYNC { get; set; }
        public string AUDIO_RATE { get; set; }
        public string ASPECT_RATIO { get; set; }
        public string COMPRESSION { get; set; }
        public string VIDEO_SYNC { get; set; }
        public string CHROMA_SYNC { get; set; }
        public string TIME_CODE_JUMP { get; set; }
        public string BARS { get; set; }
        public string BUMPER_IN_OUT { get; set; }
        public string WHITE_BALANCE { get; set; }
        public string BIT_RATE { get; set; }
        public string FRAME_RATE { get; set; }
        public string AUDIO_TYPE { get; set; }
        public string NOTE_FREQUENCY { get; set; }
        public string NOTE_ENGLISH { get; set; }
        public string NOTE_ATMO { get; set; }
        public string NOTE_LIP_SYNC { get; set; }
        public string NOTE_AUDIO_SYNC { get; set; }
        public string NOTE_AUDIO_RATE { get; set; }
        public string NOTE_VIDEO_LVL { get; set; }
        public string NOTE_RESOLUTION { get; set; }
        public string NOTE_VIDEO_SYNC { get; set; }
        public string NOTE_CHROMA_SYNC { get; set; }
        public string NOTE_VIDEO_NOISE { get; set; }
        public string NOTE_TIME_JUMP { get; set; }
        public string NOTE_FLAME_RATE { get; set; }
        public string PIT { get; set; }
        public string CTS { get; set; }
        public string OPC { get; set; }
        public string NOTE_PIT { get; set; }
        public string NOTE_CTS { get; set; }
        public string NOTE_OPC { get; set; }
        public string NOTE_AUDIO_NOISE { get; set; }
        public string PRG_PIC { get; set; }
        public string FIELD_REVERS_VIDEO { get; set; }
        public string EVALUAT_USER { get; set; }
        public DateTime? EVALUAT_DATE { get; set; }
        public string AUDIO_CODE { get; set; }
        public string VIDEO_CODE { get; set; }
        public string CODEC { get; set; }
        public string CODEC_NOTE { get; set; }
        public string CONTAINER_WRAP { get; set; }
        public string CONTAINER_WRAP_NOTE { get; set; }
        public string AUDIO_TYPE_NOTE { get; set; }
        public string AUDIO_LEVEL_NOTE { get; set; }
        public string V_CHROMA_LEVEL_NOTE { get; set; }
        public string BLACK_LEVEL_NOTE { get; set; }
        public string COLOR_BALANCE_NOTE { get; set; }
        public string CHILDREN { get; set; }
        public string CHILDREN_NOTE { get; set; }
        public string RESPECT { get; set; }
        public string RESPECT_NOTE { get; set; }
        public string MYSTIC { get; set; }
        public string MYSTIC_NOTE { get; set; }
        public string SEXUAL { get; set; }
        public string SEXUAL_NOTE { get; set; }
        public string VIOLANCE { get; set; }
        public string VIOLANCE_NOTE { get; set; }
        public string CIGAR { get; set; }
        public string CIGAR_NOTE { get; set; }
        public string MANER { get; set; }
        public string MANER_NOTE { get; set; }
        public string PRIVACY { get; set; }
        public string PRIVACY_NOTE { get; set; }
        public string GAMBLING { get; set; }
        public string GAMBLING_NOTE { get; set; }
        public string STATE_SYMBOL { get; set; }
        public string STATE_SYMBOL_NOTE { get; set; }
        public string RIGHT_P { get; set; }
        public string RIGHT_P_NOTE { get; set; }
        public string OTHER_P { get; set; }
        public string OTHER_P_NOTE { get; set; }
        public string TECHNICAL_ASPECT { get; set; }
        public string CONTENT_ASPECT { get; set; }
        public string BRANDING { get; set; }
        public string BRANDING_NOTE { get; set; }
        public string DUR_SEG { get; set; }
        public string DUR_SEG_NOTE { get; set; }
        public string VIEWING { get; set; }
        public string VIEWING_NOTE { get; set; }
        public string EATING { get; set; }
        public string EATING_NOTE { get; set; }
        public string OTHER_I_NOTE { get; set; }
        public string OTHER_I { get; set; }
        public string ROW_ID_STATUS_HDR { get; set; }
        public DateTime INGEST_DATE { get; set; }
    }

}
